Repository eonian-core/web, pull requests merged in 2024-09, with the labels that each got.

#95 Fix avatars rotation per hour
  app/(landing)/views/hero/join-others/join-others.tsx
Labels: staging

#96 Fix rotation once per hour
  app/(landing)/views/hero/join-others/join-others.tsx
Labels: staging

#102 Fix join others rotation
  app/(landing)/content/en.mdx
  app/(landing)/views/hero/join-others/images/1.jpg
  app/(landing)/views/hero/join-others/images/10.jpg
  app/(landing)/views/hero/join-others/images/11.jpg
  app/(landing)/views/hero/join-others/images/12.jpg
  app/(landing)/views/hero/join-others/images/13.jpg
  app/(landing)/views/hero/join-others/images/14.jpg
  app/(landing)/views/hero/join-others/images/15.jpg
  app/(landing)/views/hero/join-others/images/16.jpg
  app/(landing)/views/hero/join-others/images/17.jpg
  app/(landing)/views/hero/join-others/images/2.jpg
  app/(landing)/views/hero/join-others/images/3.jpg
  app/(landing)/views/hero/join-others/images/4.jpg
  app/(landing)/views/hero/join-others/images/5.png
  app/(landing)/views/hero/join-others/images/6.png
  app/(landing)/views/hero/join-others/images/7.jpg
  app/(landing)/views/hero/join-others/images/8.jpg
  app/(landing)/views/hero/join-others/images/9.jpg
  app/(landing)/views/hero/join-others/images/images.tsx
  app/(landing)/views/hero/join-others/join-others.module.scss
  app/(landing)/views/hero/join-others/join-others.tsx
  app/(landing)/views/hero/join-others/use-interval.tsx
Labels: development

#101 join others fixes
  app/(landing)/content/en.mdx
  app/(landing)/views/hero/join-others/images/1.jpg
  app/(landing)/views/hero/join-others/images/10.jpg
  app/(landing)/views/hero/join-others/images/11.jpg
  app/(landing)/views/hero/join-others/images/12.jpg
  app/(landing)/views/hero/join-others/images/13.jpg
  app/(landing)/views/hero/join-others/images/14.jpg
  app/(landing)/views/hero/join-others/images/15.jpg
  app/(landing)/views/hero/join-others/images/16.jpg
  app/(landing)/views/hero/join-others/images/17.jpg
  app/(landing)/views/hero/join-others/images/2.jpg
  app/(landing)/views/hero/join-others/images/3.jpg
  app/(landing)/views/hero/join-others/images/4.jpg
  app/(landing)/views/hero/join-others/images/5.png
  app/(landing)/views/hero/join-others/images/6.png
  app/(landing)/views/hero/join-others/images/7.jpg
  app/(landing)/views/hero/join-others/images/8.jpg
  app/(landing)/views/hero/join-others/images/9.jpg
  app/(landing)/views/hero/join-others/images/images.tsx
  app/(landing)/views/hero/join-others/join-others.module.scss
  app/(landing)/views/hero/join-others/join-others.tsx
  app/(landing)/views/hero/join-others/use-interval.tsx
Labels: staging

#103 Join others fixes
  app/(landing)/content/en.mdx
  app/(landing)/views/hero/join-others/images/1.jpg
  app/(landing)/views/hero/join-others/images/10.jpg
  app/(landing)/views/hero/join-others/images/11.jpg
  app/(landing)/views/hero/join-others/images/12.jpg
  app/(landing)/views/hero/join-others/images/13.jpg
  app/(landing)/views/hero/join-others/images/14.jpg
  app/(landing)/views/hero/join-others/images/15.jpg
  app/(landing)/views/hero/join-others/images/16.jpg
  app/(landing)/views/hero/join-others/images/17.jpg
  app/(landing)/views/hero/join-others/images/2.jpg
  app/(landing)/views/hero/join-others/images/3.jpg
  app/(landing)/views/hero/join-others/images/4.jpg
  app/(landing)/views/hero/join-others/images/5.png
  app/(landing)/views/hero/join-others/images/6.png
  app/(landing)/views/hero/join-others/images/7.jpg
  app/(landing)/views/hero/join-others/images/8.jpg
  app/(landing)/views/hero/join-others/images/9.jpg
  app/(landing)/views/hero/join-others/images/images.tsx
  app/(landing)/views/hero/join-others/join-others.module.scss
  app/(landing)/views/hero/join-others/join-others.tsx
  app/(landing)/views/hero/join-others/use-interval.tsx
Labels: production

#104 Switch telegram from group to channel
  app/socials.tsx
Labels: production

#106 Fix vault skeleton
  app/earn/[...vault]/header/token-gradient-skeleton.tsx
  app/earn/[...vault]/loading.tsx
  app/earn/[...vault]/page.tsx
  app/earn/[...vault]/skeleton-page.tsx
Labels: staging

#107 Fix vault skeleton
  app/earn/[...vault]/header/token-gradient-skeleton.tsx
  app/earn/[...vault]/loading.tsx
  app/earn/[...vault]/page.tsx
  app/earn/[...vault]/skeleton-page.tsx
Labels: production
